import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** Primary key UUID column, auto-generated by the database. */
export const id = () => uuid('id').defaultRandom().primaryKey();

/** Timestamp set once on insert. */
export const createdAt = () => timestamp('created_at').defaultNow().notNull();

/** Timestamp updated on every write — set manually in update queries. */
export const updatedAt = () => timestamp('updated_at').defaultNow().notNull();

/** Nullable soft-delete timestamp. */
export const deletedAt = () => timestamp('deleted_at');
