/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyRecipesRouteImport } from './routes/my-recipes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'

const MyRecipesRoute = MyRecipesRouteImport.update({
  id: '/my-recipes',
  path: '/my-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-recipes': typeof MyRecipesRoute
  '/recipes/$id': typeof RecipesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-recipes': typeof MyRecipesRoute
  '/recipes/$id': typeof RecipesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-recipes': typeof MyRecipesRoute
  '/recipes/$id': typeof RecipesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-recipes' | '/recipes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-recipes' | '/recipes/$id'
  id: '__root__' | '/' | '/my-recipes' | '/recipes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyRecipesRoute: typeof MyRecipesRoute
  RecipesIdRoute: typeof RecipesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-recipes': {
      id: '/my-recipes'
      path: '/my-recipes'
      fullPath: '/my-recipes'
      preLoaderRoute: typeof MyRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyRecipesRoute: MyRecipesRoute,
  RecipesIdRoute: RecipesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
