/* eslint-disable */
// This file is auto-generated by TanStack Router's file-based routing.
// Run `pnpm dlx tsr generate` (or the dev server) to regenerate.
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as RecipesIdRoute } from "./routes/recipes.$id";
import { createRouteTree } from "@tanstack/react-router";

const routeTree = rootRoute.addChildren([
  IndexRoute,
  RecipesIdRoute,
]);

export { routeTree };
